[book]
title = "OpenMSO"
authors = ["OpenMSO Team"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
site-url = "/"
git-repository-url = "https://github.com/openmso/openmso"
edit-url-template = "https://github.com/openmso/openmso/edit/main/doc/{path}"

